name: familyGan
channels:
- pytorch
- h2oai
- conda-forge
- defaults

dependencies:
# Core scientific python
- numpy
- matplotlib
- python>=3.6
- seaborn
- pip
- scikit-learn
- scikit-image
- h2o

# Deep Learning
- cudatoolkit
- pytorch=1.1.0
- torchvision

# Visualizations / web serving
- bokeh
- holoviews
- flask

# Jupyter Environment
- autopep8
- notebook
- ipython
- jupyter_contrib_nbextensions
- jupyterlab
- jupyter
- nb_conda

- pip:
    - nbclean
    - imageio
    - tqdm
    - tensorflow-gpu
    - keras
    - dlib
    - pathos  # for running parallel map
    - auto_tqdm
    - flask